version: '3.7'

volumes:
  postgres-data:

services:
  postgres:
    container_name: shoulders_db
    image: postgres:13-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=shoulders
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strongpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
